# Generated by Django 3.2.4 on 2021-06-28 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0003_auto_20210620_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineafactura',
            name='linea_factura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='factura.factura'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='anio',
            field=models.PositiveIntegerField(default=2000),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fecha_emision',
            field=models.PositiveIntegerField(default=2000),
        ),
        migrations.AlterField(
            model_name='factura',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='num',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lineafactura',
            name='nombre_producto',
            field=models.CharField(default='', max_length=100),
        ),
    ]
